// src/scripts/perf/perfMarks.js

export const PERF_MARKS = {
  FETCH_TEAMS: "FETCH_TEAMS",
  FETCH_OWNERS: "FETCH_OWNERS",
  FETCH_GAMES: "FETCH_GAMES",
  FETCH_AWARDS: "FETCH_AWARDS",
  FETCH_DRAFT: "FETCH_DRAFT",
  PAGE_INIT: "PAGE_INIT",
  RENDER_TEAMS: "RENDER_TEAMS",
  RENDER_SCHEDULE: "RENDER_SCHEDULE"
};
